### ISSUE TITLE
time_ns

### ISSUE THREAD

**Issue by marcogenna** [JGirdwood/UH_pyOPCN3#1]
Dear Joseph,
thanks for your great job with the OPC-N3, I'm trying to test SPI connection with your software and I came across some issues, using python 2.7 in module pyOPCN3logger "from time import time_ns" time_ns exists only after python 3.6, I tried to use python 3.7 and I have index out of range line 102 on module pyOPCN3spi
for i in range(25):
            **self.bbs_um.append(byte_to_int16(raw[index*2], raw[index*2+1]))**
            index += 2
for i in range(24):
            **self.bws.append(byte_to_int16(raw[index*2], raw[index*2+1]))**
            index += 2

Do you have any idea about what I'm doing wrong?
Thanks a loto for your support
Best regards
Marco

**Comment by wolkchen-cirrus** [comment]
Hi, could you paste the exact error message you get in stdout please?

**Comment by marcogenna** [comment]
Python 2.7

/usr/bin/python /home/pi/Downloads/UH_pyOPCN3-master/log_uav_data.py
Traceback (most recent call last):
  File "/home/pi/Downloads/UH_pyOPCN3-master/log_uav_data.py", line 1, in <module>
    import pyOPCN3logger
  File "/home/pi/Downloads/UH_pyOPCN3-master/pyOPCN3logger/__init__.py", line 2, in <module>
    from time import time_ns
ImportError: cannot import name time_ns


Python 3.7

------------------------------------------------
OPCN3 Connected
Traceback (most recent call last):
  File "/home/pi/Downloads/UH_pyOPCN3-master/log_uav_data.py", line 22, in <module>
    FMI_OPC.read_config_vars()
  File "/home/pi/Downloads/UH_pyOPCN3-master/pyOPCN3spi/__init__.py", line 103, in read_config_vars
    self.bbs_um.append(byte_to_int16(raw[index*2], raw[index*2+1]))
IndexError: list index out of range

**Comment by wolkchen-cirrus** [comment]
Thank you, can you add the following line after line 96 in the file "/home/pi/Downloads/UH_pyOPCN3-master/pyOPCN3spi/init.py" and tell me what it prints out please:

> print len(raw)

Also, are you certain you are using an N3 not an N2? The SPI tables are different.

**Comment by marcogenna** [comment]
Thanks for your time, len(raw) is 168
I'm using many N3 but is first time trying to connect directly via SPI, usually I have a converter USB-SPI working on /dev/ttyACM0

**Comment by wolkchen-cirrus** [comment]
Hi there,
That seems ok, I will do some experimenting in the lab and get back to you later today or tomorrow.
Thanks, J

**Comment by wolkchen-cirrus** [comment]
Hi,
The issue should be solved now if you download the latest repo from GitHub (note the PyPi release has not been updated yet)
Thanks, J

**Comment by marcogenna** [comment]
Hi,
thanks a lot for the effort, I'll try later or tomorrow morning and i let you know!
Cheers M

**Comment by marcogenna** [comment]
Hi Joseph,
really thanks for you help, code seems to be working, I'm just stuck because it doesn't start fan an laser and I need to work on this.
I'll let you know about progress.
Thanks M
